[package]
name = "whr"
description = "Implementation of Rémi Coulom's Whole-History Rating (WHR) algorithm for Rust"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
authors = ["Aloïs Rautureau"]

[dependencies]
itertools = "0.13"
